# Generated by Django 3.2.4 on 2021-06-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stagedflatfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField()),
                ('b', models.TextField()),
                ('c', models.TextField()),
            ],
        ),
    ]
